import{a as d,i as p,S as h}from"./assets/vendor-4d53def3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function b(r,s,o,n,e,t,a){const i=document.querySelector(".gallery"),c=`<li class="gallery-item">
      <a class="gallery-link" href="${s}">
      <img src="${r}" alt="${o}" class="gallery-img">
      </a>
        <div class="text-wrap">
          <p class="img-text">Likes <span class="img-text-span">${n}</span></p>
          <p class="img-text">Views <span class="img-text-span">${e}</span></p>
          <p class="img-text">Comments <span class="img-text-span">${t}</span></p>
          <p class="img-text">Downloads <span class="img-text-span">${a}</span></p>
        </div>
    </li>`;i.insertAdjacentHTML("afterbegin",c)}async function g(r){let s=1,o=15;const t=`https://pixabay.com/api/?key=44806225-40e07737f22f709bd193bb0f7&${new URLSearchParams({_limit:o,_page:s})}`,a="photo",i="horizontal",c=!0;return(await d.get(`${t}&q=${r}&image_type=${a}&orientation=${i}&safesearch=${c}`)).data}const l=document.querySelector(".loader");l.style.opacity=0;const f=document.querySelector(".form");f.addEventListener("submit",S);async function S(r){try{document.querySelector(".gallery").innerHTML="",r.preventDefault(),l.style.opacity=1;const o=r.currentTarget.elements.query.value.trim().toLowerCase();if(o.length<=0){p.show({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Please write something in the search field"}),l.style.opacity=0;return}g(o).then(y),f.reset()}catch{$()}}let u=new h(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(r){const s=r.hits;r.totalHits===0?p.error({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):s.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:i,comments:c,downloads:m})=>{b(n,e,t,a,i,c,m)}),u.on("show.simplelightbox",function(){}),u.refresh(),l.style.opacity="0"}const x=document.querySelector(".page-btn");x.addEventListener("submit",L);function L(r){r.preventDefault(),page+=1,g().then(y)}function $(){p.error({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}
//# sourceMappingURL=commonHelpers.js.map
