import{a as h,i as f,S as b}from"./assets/vendor-4d53def3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();function S(t,r,o,a,e,s,n){const i=document.querySelector(".gallery"),l=`<li class="gallery-item">
      <a class="gallery-link" href="${r}">
      <img src="${t}" alt="${o}" class="gallery-img">
      </a>
        <div class="text-wrap">
          <p class="img-text">Likes <span class="img-text-span">${a}</span></p>
          <p class="img-text">Views <span class="img-text-span">${e}</span></p>
          <p class="img-text">Comments <span class="img-text-span">${s}</span></p>
          <p class="img-text">Downloads <span class="img-text-span">${n}</span></p>
        </div>
    </li>`;i.insertAdjacentHTML("afterbegin",l)}async function x(t){const o="https://pixabay.com/api/?key=44806225-40e07737f22f709bd193bb0f7",a="photo",e="horizontal",s=!0;let n=1;try{return(await h.get(`${o}&q=${t}&image_type=${a}&orientation=${e}&safesearch=${s}&page=${n}&per_page=15`)).data}catch(i){console.error(i)}}const g="is-hidden";function w(t){t.classList.add(g)}function L(t){t.classList.remove(g)}function $(t){t.disabled=!0}function q(t){t.disabled=!1}const p={hide:w,show:L,disable:$,enable:q},c=document.querySelector(".loader");c.style.opacity=0;const u=document.querySelector(".page-btn");p.hide(u);const d=document.querySelector(".form");d.addEventListener("submit",P);async function P(t){document.querySelector(".gallery").innerHTML="",t.preventDefault(),c.style.opacity=1;const o=t.currentTarget.elements.query.value.trim().toLowerCase();if(o.length<=0){f.show({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Please write something in the search field"}),c.style.opacity=0,d.reset();return}p.show(u),p.disable(u);try{await x(o).then(v)}catch{C()}}let m=new b(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function v(t){const r=t.hits;t.totalHits===0?f.error({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):r.map(({webformatURL:a,largeImageURL:e,tags:s,likes:n,views:i,comments:l,downloads:y})=>{S(a,e,s,n,i,l,y)}),m.on("show.simplelightbox",function(){}),m.refresh(),c.style.opacity="0"}function C(){f.error({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}
//# sourceMappingURL=commonHelpers.js.map
